# Generated by Django 5.2.7 on 2025-10-31 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория слов',
                'verbose_name_plural': 'Категории слов',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.CharField(max_length=200, verbose_name='Русское слово')),
                ('chinese_simplified', models.CharField(max_length=100, verbose_name='Китайский (упрощенный)')),
                ('chinese_traditional', models.CharField(blank=True, max_length=100, verbose_name='Китайский (традиционный)')),
                ('pinyin', models.CharField(max_length=200, verbose_name='Пиньинь')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adjective', 'Прилагательное'), ('adverb', 'Наречие'), ('pronoun', 'Местоимение'), ('numeral', 'Числительное'), ('preposition', 'Предлог'), ('conjunction', 'Союз'), ('interjection', 'Междометие')], default='noun', max_length=20)),
                ('hsk_level', models.IntegerField(default=1, verbose_name='Уровень HSK')),
                ('frequency', models.IntegerField(default=0, verbose_name='Частота употребления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['russian'],
                'indexes': [models.Index(fields=['russian'], name='dictionary__russian_e47bb5_idx'), models.Index(fields=['chinese_simplified'], name='dictionary__chinese_efa824_idx'), models.Index(fields=['pinyin'], name='dictionary__pinyin_5b39f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='WordExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_ru', models.TextField(verbose_name='Пример на русском')),
                ('example_zh', models.TextField(verbose_name='Пример на китайском')),
                ('example_pinyin', models.TextField(verbose_name='Пиньинь примера')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.word')),
            ],
            options={
                'verbose_name': 'Пример использования',
                'verbose_name_plural': 'Примеры использования',
            },
        ),
    ]
