# Generated by Django 5.2.7 on 2025-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adjective', 'Прилагательное'), ('adverb', 'Наречие'), ('pronoun', 'Местоимение'), ('numeral', 'Числительное'), ('preposition', 'Предлог'), ('conjunction', 'Союз'), ('interjection', 'Междометие'), ('measure word', ' Счетное слово')], default='noun', max_length=20),
        ),
    ]
